@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor 用户 as 用户
activate 用户
activate 前端
用户 -> 前端: 选择分发方式为微信组稿
前端 -> 前端: 编辑微信组稿
前端 -> 前端: 编辑分发申请单
activate 稿件
前端 -> 稿件: 提交分发审批
稿件 -> 稿件: 分发申请单持久化
稿件 -> 稿件: 组稿详情持久化(对应子稿件)
activate 分发
稿件 -> 分发: 分发接口调用
前端 <-- 稿件: 分发中
前端 --> 用户: 分发中

@enduml