
'https://plantuml.com/state-diagram
@startuml
package 稿件 {
    object 稿件A {
      稿件id
      标题
      封面
    }
    object 稿件B {
          稿件id
          标题
          封面
        }
    object 稿件C{
               稿件id
               标题
               封面
             }
    object 稿件D {
                    稿件id
                    标题
                    封面
                  }
}

package 微信组稿 {
    map 账号 {
        微信A *-> 稿件.稿件A
        微信A *-> 稿件.稿件B
        微信A *-> 稿件.稿件C
        微信A *-> 稿件.稿件D
        微信B *-> 稿件.稿件A
        微信B *-> 稿件.稿件B
        微信B *-> 稿件.稿件C
        微信B *-> 稿件.稿件D
        微信C *-> 稿件.稿件A
        微信C *-> 稿件.稿件B
        微信C *-> 稿件.稿件C
        微信C *-> 稿件.稿件D
    }

}

package 分发详情{
    object 参数
    map 参数{
        稿件id
        标题
        封面
    }
}
'A::c --> foo
@enduml
